wandb_version: 1

dataset:
  desc: null
  value: flickr30k
manifold:
  desc: null
  value: Lorentz
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.25.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689844439.336644
    t:
      1:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 77
      2:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      6: 4.25.0
      8:
      - 5
