wandb_version: 1

dataset:
  desc: null
  value: flickr30k
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.25.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687087195.860705
    t:
      1:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 77
      2:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 77
      3:
      - 16
      - 23
      - 24
      4: 3.8.16
      5: 0.15.4
      6: 4.25.0
      8:
      - 5
